// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://reaywgxygxnuxoqtegjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlYXl3Z3h5Z3hudXhvcXRlZ2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxODMwMTAsImV4cCI6MjA4NTc1OTAxMH0.XtJ9mWvM24Q8P9pW0ocnYZN-yigafDr1ICEVU9dDANg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});